# Generated by Django 4.2.27 on 2026-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationhistory',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
