# Generated by Django 4.2.27 on 2026-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calculationhistory_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationhistory',
            name='note',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
